### PR TITLE
we need to set_password after save the user otherwise it'll save the raw_password in db.

### PR DESCRIPTION
**Pull request by zhiwehu**
# Hey, I just made a Pull Request!

## Checklist for PR author(s)

- [ ] Changes are covered by unit tests (no major decrease in code coverage %).
- [ ] All tests pass.
- [ ] Docstring coverage is **100%** via `interrogate drf_user` (I mean, we _should_ set a good example :smile:).
- [ ] Updates to documentation:
    - [ ] Document any relevant additions/changes in `README.md`.
    - [ ] Manually update **both** the `README.md` _and_ `docs/index.rst` for any new changes.
    - [ ] Any changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in the project's [``__init__.py``](https://github.com/101loop/drf-user/blob/master/drf_user/__init__.py) file.

## Release note

```release-note

```

### CODE REVIEW

**Comment by zhiwehu** [comment]
we need to set_password after save the user otherwise it'll save the raw_password in db.

**Comment by sumit4613** [comment]
Hey @zhiwehu sorry your PR was pending for a long time, I was kinda busy in my day job. That's why I wasn't able to see it.  Thanks for the fix mate, I missed this somehow.

**Comment by sumit4613** [comment]
I'll merge this, I just need to update one test related to password change.

**Comment by sumit4613** [comment]
Hey, @zhiwehu looks like by mistake I merged the wrong PR. But your changes got merged to master. Thanks for the help mate. 🙌🏽 🙌🏽 . 

Closing this MR now.

**Pull request closed without merging**
